/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CandleChart: typeof import('./src/components/CandleChart.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Greet: typeof import('./src/components/Greet.vue')['default']
    GroupMange: typeof import('./src/components/group/GroupMange.vue')['default']
    GroupSelect: typeof import('./src/components/group/GroupSelect.vue')['default']
    GroupTab: typeof import('./src/components/GroupTab.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    StockTable: typeof import('./src/components/StockTable.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Tool: typeof import('./src/components/Tool.vue')['default']
  }
}
