/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CandleChart: typeof import('./src/components/CandleChart.vue')['default']
    DataDetail: typeof import('./src/components/StockData/DataDetail.vue')['default']
    Detail: typeof import('./src/components/StockData/Detail.vue')['default']
    DisPlay: typeof import('./src/components/settingComponents/DisPlay.vue')['default']
    DragTest: typeof import('./src/components/DragTest.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FUn: typeof import('./src/components/settingComponents/FUn.vue')['default']
    GroupTab: typeof import('./src/components/GroupTab.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    NewCandleChart: typeof import('./src/components/NewCandleChart.vue')['default']
    NewNewCandleChart: typeof import('./src/components/NewNewCandleChart.vue')['default']
    RHeader: typeof import('./src/components/transactionRecordComponents/RHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RTable: typeof import('./src/components/transactionRecordComponents/RTable.vue')['default']
    RToolBar: typeof import('./src/components/transactionRecordComponents/RToolBar.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    StockGroupMange: typeof import('./src/components/group/StockGroupMange.vue')['default']
    StockGroupSelect: typeof import('./src/components/group/StockGroupSelect.vue')['default']
    StockTable: typeof import('./src/components/StockTable.vue')['default']
    Tool: typeof import('./src/components/Tool.vue')['default']
    TransactionRecord: typeof import('./src/components/TransactionRecord.vue')['default']
  }
}
