/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CandleChart: typeof import('./src/components/CandleChart.vue')['default']
    CandleChartNewNew: typeof import('./src/components/CandleChartNewNew.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSearch: typeof import('./src/components/ElSearch.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    Greet: typeof import('./src/components/Greet.vue')['default']
    GroupSelectNew: typeof import('./src/components/group/GroupSelectNew.vue')['default']
    GroupTab: typeof import('./src/components/GroupTab.vue')['default']
    GroupTabNew: typeof import('./src/components/GroupTabNew.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    NewCandleChart: typeof import('./src/components/NewCandleChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    StockGroupMange: typeof import('./src/components/group/StockGroupMange.vue')['default']
    StockGroupSelect: typeof import('./src/components/group/StockGroupSelect.vue')['default']
    StockTable: typeof import('./src/components/StockTable.vue')['default']
    Tool: typeof import('./src/components/Tool.vue')['default']
  }
}
