//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "stock_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub code: String,
    pub name: String,
    pub r#box: Option<String>,
    pub hold: bool,
}

impl Model {
    pub fn new(code:String,name:String)->Self{
        Self{
            code,
            name,
            r#box: None,
            hold: false,
        }
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::group_stock_relation::Entity")]
    GroupStockRs,
}
impl Related<super::group_stock_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupStockRs.def()
    }
}
impl ActiveModelBehavior for ActiveModel {}
